WebApplication2/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlashPoints.Data;
using FlashPoints.Models;

using QRCoder;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace FlashPoints.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            AddUserIfNotExists(User.Identity.Name);
            var events = await _context.Event.Where(e => e.Approved == true)
                .OrderBy(e => e.StartDateTime)
                .ToListAsync();
            return View(events);
        }

        // GET: Events
        [Authorize(Policy = "Administrator")]
        public async Task<IActionResult> StudentEvents()
        {
            AddUserIfNotExists(User.Identity.Name);
            var events = await _context.Event.Where(e => e.Approved != true)
                .OrderBy(e => e.StartDateTime)
                .ToListAsync();
            return View(events);
        }

        [Authorize(Policy = "Administrator")]
        public async Task<IActionResult> ApproveEvent(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@event == null)
            {
                return NotFound();
            }

            @event.Approved = true;
            await _context.SaveChangesAsync();
            return RedirectToAction("StudentEvents");
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@event == null)
            {
                return NotFound();
            }

            

            var user = _context.User.Where(u => u.Email == User.Identity.Name);
            if (user.First().IsAdmin == true)
            {
                ViewBag.isAdmin = true;
            }

            return View(@event);
        }

        [Authorize(Policy = "Administrator")]
        public async Task<IActionResult> QRCode(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@event == null)
            {
                return NotFound();
            }

            var user = _context.User.Where(u => u.Email == User.Identity.Name).First();

            if (@event.Creator == User.Identity.Name || user.IsAdmin)
            {
                string qrcode = @event.Title;

                using (MemoryStream ms = new MemoryStream())
                {
                    QRCodeGenerator qrGenerator = new QRCodeGenerator();
                    QRCodeData qrCodeData = qrGenerator.CreateQrCode(qrcode, QRCodeGenerator.ECCLevel.Q);
                    QRCode qrCode = new QRCode(qrCodeData);
                    using (Bitmap bitMap = qrCode.GetGraphic(20))
                    {
                        bitMap.Save(ms, ImageFormat.Png);
                        ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                    }
                }

                return View(@event);
            } else
            {
                return View("AccessDenied");
            }
        }

        [Authorize(Policy = "Administrator")]
        public IActionResult AdminEvent()
        {
            return View();
        }

        [Authorize(Policy = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> AdminEvent(Event @event)
        {
            if (ModelState.IsValid)
            {
                @event.Approved = true;
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = @event.ID });
            }
            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,StartDateTime,EndDateTime,PointValue,QRcode,Approved,Creator,Location,NumberAttended")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();

                string subject = "A new FlashPoints Event Request is waiting to be approved!";
                string body = $"<a href='https://flashpoints-web-app.azurewebsites.net/Events/Details/{@event.ID}'>Click here to view the request.</ a ><br /> <br /> <br />";
                EmailSender.SendMail("flashpointscoordinators@gmail.com", subject, body);


                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,StartDateTime,EndDateTime,PointValue,QRcode,Approved,Creator,Location,NumberAttended")] Event @event)
        {
            if (id != @event.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Event.FindAsync(id);
            _context.Event.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.ID == id);
        }
        public void AddUserIfNotExists(string email)
        {
            var query = _context.User.Where(e => e.Email == email);

            if (query.Count() == 0)
            {
                
                User newUser = new User();
                newUser.FirstName = User.FindFirst(ClaimTypes.GivenName).Value;
                newUser.LastName = User.FindFirst(ClaimTypes.Surname).Value;
                newUser.Email = email;
                newUser.PrizesRedeemed = new List<PrizeRedeemed>();
                newUser.EventsAttended = new List<EventAttended>();
                _context.User.Add(newUser);
                _context.SaveChanges();
            }
        }

    }
}

WebApplication2/Controllers/PrizesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlashPoints.Data;
using FlashPoints.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace FlashPoints.Controllers
{
    [Authorize]
    public class PrizesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PrizesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Prizes
        public async Task<IActionResult> Index()
        {
            AddUserIfNotExists(User.Identity.Name);

            PrizeIndexViewModel mod = new PrizeIndexViewModel();

            mod.user = _context.User.Where(u => u.Email == User.Identity.Name)
                .Include(p => p.PrizesRedeemed)
                .First();

            mod.prizes = await _context.Prize
                .Include(p => p.PrizesRedeemed)
                .OrderBy(p => p.PointPrice)
                .ToListAsync();

            return View(mod);
        }

        [Authorize(Policy = "Administrator")]
        public async Task<IActionResult> ManagePrizes()
        {
            var prizes = await _context.Prize
                .ToListAsync();

            return View(prizes);
        }

        // GET: Prizes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var prize = await _context.Prize
                .Include(p => p.PrizesRedeemed)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (prize == null)
            {
                return NotFound();
            }

            var user = _context.User.Where(u => u.Email == User.Identity.Name)
                .Include(p => p.PrizesRedeemed)
                .First();

            PrizeRedeemed rdm;

            try
            {
                rdm = user.PrizesRedeemed.Where(p => p.PrizeID == prize.ID).First();
            } catch
            {
                rdm = null;
            }

            if (rdm == null)
            {
                ViewBag.redeemed = false;
            } else
            {
                ViewBag.redeemed = true;
            }

            
            if (user.Points < prize.PointPrice)
            {
                ViewBag.redeemable = false;
            } else
            {
                ViewBag.redeemable = true;
            }

            ViewBag.userPoints = user.Points;

            return View(prize);
        }

        // POST: Prizes/RedeemPrize/5
        public async Task<IActionResult> RedeemPrize(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prize = await _context.Prize
                .FirstOrDefaultAsync(m => m.ID == id);
            if (prize == null)
            {
                return NotFound();
            }

            var user = _context.User.Where(u => u.Email == User.Identity.Name)
                .Include(u => u.PrizesRedeemed)
                .First();

            if (user.Points >= prize.PointPrice)
            {
                user.PrizesRedeemed.Add(new PrizeRedeemed
                {
                    User = user,
                    Prize = prize
                });
                _context.SaveChanges();
            }
            
            return RedirectToAction("Details", new { id = prize.ID });
        }

        // GET: Prizes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Prizes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Description,PointPrice,ImagePath,CurrentInventory,Location,ActualCost")] Prize prize)
        {
            if (ModelState.IsValid)
            {
                prize.PrizesRedeemed = new List<PrizeRedeemed>();
                _context.Add(prize);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(prize);
        }

        // GET: Prizes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prize = await _context.Prize.FindAsync(id);
            if (prize == null)
            {
                return NotFound();
            }
            return View(prize);
        }

        // POST: Prizes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Description,PointPrice,ImagePath,CurrentInventory,Location,ActualCost")] Prize prize)
        {
            if (id != prize.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prize);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrizeExists(prize.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(prize);
        }

        // GET: Prizes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prize = await _context.Prize
                .FirstOrDefaultAsync(m => m.ID == id);
            if (prize == null)
            {
                return NotFound();
            }

            return View(prize);
        }

        // POST: Prizes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var prize = await _context.Prize.FindAsync(id);
            _context.Prize.Remove(prize);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PrizeExists(int id)
        {
            return _context.Prize.Any(e => e.ID == id);
        }

        public void AddUserIfNotExists(string email)
        {
            var query = _context.User.Where(e => e.Email == email);
            if (query.Count() == 0)
            {
                User newUser = new User();
                newUser.FirstName = User.FindFirst(ClaimTypes.GivenName).Value;
                newUser.LastName = User.FindFirst(ClaimTypes.Surname).Value;
                newUser.Email = email;
                newUser.PrizesRedeemed = new List<PrizeRedeemed>();
                newUser.EventsAttended = new List<EventAttended>();
                _context.User.Add(newUser);
                _context.SaveChanges();
            }
        }
    }
}

WebApplication2/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
}

<h2 style="color:red">Access Denied (Student User)</h2>
<p>Only Administrators are authorized to access this part of the application. Please click the Back button in your browser.</p>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlashPoints</title>
    <link href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="~/favicon.ico">
    <style>

        * {
            font-family: 'Signika', sans-serif;
        }

        body {
            color: #003876;
            padding-left: 15px;
        }

        h1 h2 h3 h4 h5 h6 {
            color: #003876;
        }

        .footer {
            position: absolute;
            width: 94%;
            bottom: 0px;
            text-align: center;
            min-height: 60px;
            padding-right: 0px;
        }

        html {
            position: relative;
            min-height: 100%;
            padding-bottom: 75px;
            padding-left: 24px;
        }
        
       
        .img-responsive {
            float: inherit;
            width: 100px;
            height: 100px;
            background-position: 50% 50%;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .img {
            width: 300px;
            height: auto;
        }

        .row {
            margin: 4px;
        }

        .col-md-6 {
            text-align: center;
            image-orientation: inherit;
            border-color: #003876;
            border-style: solid;
            border-radius: 5px;
            padding-top: 5px;
            margin: 4px;
        }

        .navbar-custom {
            background-color: #003876;
            color: #003876;
            border-radius: 0;
        }

            .navbar-custom .navbar-nav > li > a {
                color: #f0b310;
            }

            .navbar-custom .navbar-nav > .active > a {
                color: #ffffff;
                background-color: transparent;
            }

                .navbar-custom .navbar-nav > li > a:hover,
                .navbar-custom .navbar-nav > li > a:focus,
                .navbar-custom .navbar-nav > .active > a:hover,
                .navbar-custom .navbar-nav > .active > a:focus,
                .navbar-custom .navbar-nav > .open > a {
                    text-decoration: none;
                    background-color: #003876;
                }

            .navbar-custom .navbar-brand {
                color: #f0b310;
            }

            .navbar-custom .navbar-toggle {
                background-color: #f0b310;
            }

            .navbar-custom .icon-bar {
                background-color: #003876;
            }
    </style>    
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>            
        <nav class="navbar navbar-custom navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>                    

                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FlashPoints</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Events" asp-action="Index">Events</a></li>
                        <li><a asp-area="" asp-controller="Prizes" asp-action="Index">Prizes</a></li>
                        <li><a asp-area="" asp-controller="Events" asp-action="Create">Submit Event Request</a></li>
                    </ul>
                    <partial name="_LoginPartial" />

                    <a class="brand" style="margin: 0; float: none; text-align:center; @*padding-left: 140px;*@" href="#">
                        @*<img src="https://tbncdn.freelogodesign.org/623aa49e-565e-40e9-bc55-715c2e824f89.png?1542724194020" style="width:50px;height:50px;" />*@
                        <img src="~/images/prizes/FlashPointsLogo.png" style="width:50px;height:50px;" />
                    </a>

                </div>               
            </div>
        </nav>

        @RenderBody()


        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>
        @RenderSection("Scripts", required: false)



</body>

    <div class="footer">
        <hr style="border: 1px solid #f0b310">
        <p>&copy; 2018 - Kent State University</p>
        <a asp-controller="Home" asp-action="Contact">Contact Us</a>
    <div />

</html>